aws cloudformation delete-stack cdh1
aws cloudformation delete-stack cdh2
aws cloudformation delete-stack cdh3
aws cloudformation delete-stack cdh4
aws cloudformation delete-stack cdh5
aws cloudformation delete-stack cdh6
aws cloudformation delete-stack cdh7
aws cloudformation delete-stack cdh8
aws cloudformation delete-stack cdh9
aws cloudformation delete-stack cdh10
