aws cloudformation delete-stack --stack-name cdh1
aws cloudformation delete-stack --stack-name cdh2
aws cloudformation delete-stack --stack-name cdh3
aws cloudformation delete-stack --stack-name cdh4
aws cloudformation delete-stack --stack-name cdh5
aws cloudformation delete-stack --stack-name cdh6
aws cloudformation delete-stack --stack-name cdh7
aws cloudformation delete-stack --stack-name cdh8
aws cloudformation delete-stack --stack-name cdh9
aws cloudformation delete-stack --stack-name cdh10
