---
# Cloudera playbook

- name: Configure Cloudera Manager Repository
  hosts: tag_main_group_cdh_servers
  roles:
    - cm_repo
  tags: cm_repo

- name: Install rngd
  hosts: tag_main_group_cdh_servers
  roles:
    - rngd
  tags: rngd

- name: Install Java
  hosts: tag_main_group_cdh_servers
  roles:
    - java
  tags: java

- name: Install MariaDB and create databases
  hosts: tag_Role_db_server
  roles:
    - mariadb
  tags:
    - mysql
    - mysql_server

- name: Install MySQL Connector
  hosts: tag_main_group_cdh_servers
  roles:
    - mysql_connector
  tags:
    - mysql
    - mysql_client

- name: Install MIT KDC Server
  hosts: tag_Role_krb5_server
  roles:
    - krb5/server
  tags: krb5

- name: Install MIT KDC Client
  hosts: tag_main_group_cdh_servers
  roles:
    - { role: krb5/client, when: (krb5_kdc_type is defined) and (krb5_kdc_type != 'none') }
  tags:
    - krb5
    - krb5_client

- name: Configure EPEL Repository
  hosts: tag_Role_scm_server
  roles:
    - epel
  tags: epel

- name: Install Cloudera Manager Agents
  hosts: tag_main_group_cdh_servers
  roles:
    - cm_agents
  tags: cm_agents

- name: Install Cloudera Manager Server
  hosts: tag_Role_scm_server
  roles:
    - scm
  tags: cluster_template

- name: Install CDH
  hosts: tag_Role_scm_server
  roles:
    - cdh
  tags: cluster_template

